
const SampleItinerary = () => (
  <section className="sample-itinerary" style={{ padding: '2rem', backgroundColor: 'var(--cream)' }}>
    <h2 style={{ fontSize: '2rem', marginBottom: '1rem', color: 'var(--navy)' }}>Sample Itinerary</h2>
    <p style={{ color: 'var(--navy)' }}>
      Below is a quick preview of a typical itinerary generated by our AI agents. Your personalized plan will include day‑by‑day activities, recommended hotels, dining spots, and budget breakdown.
    </p>
    <ul style={{ listStyle: 'disc inside', color: 'var(--navy)', lineHeight: '1.6' }}>
      <li>Day 1: Arrival, city tour, welcome dinner.</li>
      <li>Day 2: Guided museum visit, lunch at a local bistro.</li>
      <li>Day 3: Outdoor adventure, sunset beach walk.</li>
      <li>... and more tailored to your preferences.</li>
    </ul>
  </section>
);

export default SampleItinerary;
